# Generated by Django 4.1.3 on 2022-11-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actorid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('photo', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(max_length=100, verbose_name='Türler'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.CharField(max_length=10, verbose_name='Uzunluk'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Film İsmi'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='plot',
            field=models.CharField(max_length=500, verbose_name='Konu'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(default='', verbose_name='Afiş'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Puan'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.URLField(default='', verbose_name='Fragman'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Yıl'),
        ),
    ]
