# Generated by Django 4.1.3 on 2022-12-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_cover',
            field=models.ImageField(upload_to='movies'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_name',
            field=models.ImageField(upload_to='movies'),
        ),
    ]
